### ISSUE TITLE
Default Worker Adapter not working

### ISSUE THREAD

**Issue by letiesperon** [wanelo/counter-cache#13]
Hi! I'm having a hard time setting up. I want it to use my already working delayed jobs and Redis. 
So I added Redis to my gemfile like this
````
gem 'counter-cache', '~> 0.3.0'
gem 'redis', '~> 3.2', '>= 3.2.2'
````

In my config file
```
class TestWorkerAdapter
  def enqueue(delay, base_class, options)
    options[:source_object_class_name] = base_class.constantize
    counter_class = options[:counter].constantize # options[:counter] is the class name of the counter that called the adapter.
    counter = counter_class.new(nil, options)
    counter.save!
  end
end

Counter::Cache.configure do |c|
  c.default_worker_adapter = TestWorkerAdapter ?? DelayedJobs???
  c.recalculation_delay    = 5.hours
  c.redis_pool             = Redis.new
  c.counting_data_store    = Counter::Cache::Redis
end
````

If I run it like that it says 
`undefined method `get' for Counter::Cache::Redis:Class`

If I don't put the line `c.default_worker_adapter` when executing it says 
`undefined method `enqueue' for nil:NilClass`

If I don't put the ` c.counting_data_store` line  it says 
`undefined method `enqueue' for nil:NilClass`

Any idea on what's going on? What should I put in the Worker Adapter?
Thank you for your time

**Comment by hjhart** [comment]
Hi @letiesperon,

I'm not totally sure, but looking at this [documentation](https://github.com/wanelo/counter-cache#configuration) you may want to change `TestWorkerAdapter.new` to `TestWorkerAdapter`.

**Comment by letiesperon** [comment]
Yes, sorry but that doesn't work either. I need an adapter for delayed jobs, do you know where I can find it? Thank you!!!

**Comment by letiesperon** [comment]
I creates this worker adapter
```
class CounterWorker
  CounterJob = Struct.new(:base_class, :options) do
    def perform
      p 'Updating counters...'
      options[:source_object_class_name] = base_class.constantize
      counter_class = options[:counter].constantize
      counter = counter_class.new(nil, options)
      counter.save!
      p 'Updated counters'
    end
  end

  def enqueue(delay_time, base_class, options)
    Delayed::Job.enqueue(CounterJob.new(base_class, options), run_at: delay_time.from_now)
  end
end
```

But it updates the database value every time. How can I check that it is not enqueued if it was already? I thought this was already implemented but maybe I have to add this logic in the adapter too?

**Comment by mattcamuto** [comment]
@letiesperon - The unique job constraint should be a function of the background worker framework you are using. I am not sure if Delayed::Job supports uniquing or not. We have used sidekiq which supports uniq jobs.

**Comment by letiesperon** [comment]
Thank you for your reply. Delayed jobs does not support it without any additional plugin so I added the logic in the adapter using redis keys. I will close this issue.
