### ISSUE TITLE
Nested counts support

### ISSUE THREAD

**Issue by guyisra** [wanelo/counter-cache#2]
Does this support a situation where lets say

 a product has many posts, 
and a store has many products,

so to count how many posts a store has, I need to first have the posts counter per product cached, and then sum them for the store, while each post per product created should cause store's count recalculation

Is that possible (without too much modifications)?

**Comment by mattcamuto** [comment]
I do not believe it does (will have to go back and look at the code). We could possibly add in a cascading count. Or you would add a Store has_many posts as a duplicate relationship in your models. Not ideal but also would add a column. I will see if it is possible with current code or slight modification and get back.

**Comment by guyisra** [comment]
doesn't wanelo have such a use case? like knowing how many saves a certain store has? or something similar?

**Comment by mattcamuto** [comment]
You would try a custom counter method.. For example:

```ruby
class Store
  # DB column named product_post_counts
end

class Products
  counter_cache_on column: :product_post_counts,
                   relation: :store,
                   wait: 10.minutes,
                   method: :calculate_product_posts

   def calculate_product_posts
     # your code here to compute the product post count
   end
end
```

**Comment by hjhart** [comment]
@guyisra Hopefully @mattcamuto's solution above helped you. I'm going to close this now, as it is over 2 years old.
