### ISSUE TITLE
longer or custom class prefix names

### ISSUE THREAD

**Issue by mattcamuto** [wanelo/counter-cache#8]
Currently the redis key prefix is only two characters of the class name. It would be nice to either

1) Change this to more then 2 character

or

2) Allow a :name option in the config options for counter_cache_on

The issue here is if you have two classes

Stores
Stories

you can easily use the same redis key for your counters.

@kigster @sax

**Comment by hjhart** [comment]
I agree @mattcamuto! 

If you have time, feel free to issue a PR. 

Closing this for posterity, since discussion has gotten a bit stale. :)
